# 开发环境配置
server:
    # 服务器的HTTP端口，默认为8080
    port: 8090
    servlet:
        # 应用的访问路径
        context-path: /
    tomcat:
        # tomcat的URI编码
        uri-encoding: UTF-8
        # 连接数满后的排队数，默认为100
        accept-count: 1000
        threads:
            # tomcat最大线程数，默认为200
            max: 800
            # Tomcat启动初始化的线程数，默认值10
            min-spare: 100
# 日志配置
logging:
    level:
        com.ruoyi: debug
        org.springframework: warn

# Spring配置
spring:
    application:
        name: TwitterMonitoring
    # 资源信息
    messages:
        # 国际化资源文件路径
        basename: i18n/messages
    # 服务模块
    devtools:
        restart:
            # 热部署开关
            enabled: true
    # redis 配置
    data:
        redis:
            # 地址
            host: localhost
            # 端口，默认为6379
            port: 6379
            # 数据库索引
            database: 0
            # 密码
            password:
            # 连接超时时间
            timeout: 10s
